{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.configMapName" . }}
data:
  MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES_HISTOGRAM_HTTP_SERVER_REQUESTS: "true"
  MANAGEMENT_METRICS_DISTRIBUTION_SLO_HTTP_SERVER_REQUESTS: 100ms,300ms,500ms,1s,2s,5s
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: {{ .Values.app.persistence.provider }}
  {{- if (eq "mysql" .Values.app.persistence.provider) }}
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: {{ include "catalog.mysql.endpoint" . }}
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: {{ .Values.app.persistence.database }}
  {{- end }}
{{- end }}
