{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "orders.fullname" . }}-metrics
  labels:
    {{- include "orders.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "orders.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path | quote }}
      interval: {{ .Values.metrics.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
